export type IconProps = {
  iconType: "boxTick"
            | "cartLarge"
            | "cartSmall"
            | "category"
            | "delivery"
            | "heart"
            | "heartFilled"
            | "minus"
            | "plus"
            | "search"
            | "shop"
            | "trash"
            | "user"
            | "whatsapp"
}
