export type IconProps = {
  iconType:
    | "chev"
    | "check"
    | "boxTick"
    | "boxTickLarge"
    | "cartLarge"
    | "cartSmall"
    | "almacen"
    | "category"
    | "delivery"
    | "heart"
    | "heartFilled"
    | "minus"
    | "plus"
    | "search"
    | "shop"
    | "trash"
    | "user"
    | "whatsapp"
    | "rightArrow"
    | "congelados"
    | "libreria"
    | "vinoteca"
    | "limpieza"
    | "bebidas-sin-alcohol"
    | "bebidas-con-alcohol"
    | "variados"
    | "hamburger"
    | "step-1"
    | "step-2"
    | "step-3"
  style?: string
}
